### ISSUE TITLE
Add API to return licenses as a map in addition to list

### ISSUE THREAD

**Issue by dwalluck** [spdx/Spdx-Java-Library#237]
I see that the license list is actually using a map internally, but the API returns a list `Map::values()`. Is it possible to add an API which also returns a `Map` with key `String licenseId` and value `SpdxListedLicense`? This would be more performant rather than having to recreate a map from the list.

**Comment by goneall** [comment]
Sounds like a useful API - if you'd like to create a PR, I can review merge.  Otherwise, I'll take a look at this after implementing the SPDX 3.0 support.

**Comment by goneall** [comment]
@dwalluck - Finished with the SPDX 3 upgrade - can you point me to the API that returns the list?

**Comment by dwalluck** [comment]
@goneall Thanks for following up. As an aside, I quickly tried to test 2.0.0-RC1 and I got a fatal error loading the cached SPDX licenses:

```
[main] WARN  org.spdx.library.ListedLicenses - Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: No implementation found for SPDX spec version 3.0.1 Note: you can set the org.spdx.useJARLicenseInfoOnly property to true to avoid this warning.
[main] ERROR org.spdx.library.ListedLicenses - Error loading cached SPDX licenses
```

I no longer see an API which returns a list. But, there's also currently no API which returns a map.

I guess it comes down to a design choice here since `SpdxListedLicenseModelStore` already has a couple maps present, `Map<String, LicenseJson> listedLicenseCache` and `Map<String, ExceptionJson> listedExceptionCache`.

However, the `ListedLicense*` objects themselves are not cached and can only be created on the fly via `ListedLicense::getListedLicenseById*` or `getListedExceptionById*` which returns a new object every time these methods are called. Maybe you could also add a `Map<String, ListedLicense>`/`Map<String, ListedLicenseException>` in `ListedLicense` since this data is static.

**Comment by goneall** [comment]
> I quickly tried to test 2.0.0-RC1 and I got a fatal error loading the cached SPDX licenses...

I wasn't able to duplicate the problem.

The warning is expected if you're not connected to the internet.  The hard error, on the other hand, is completely unexpected.

I'll add some additional logging to see if we can find out what is wrong.

The code just reads the license information from resource files included in the Jar file.

**Comment by goneall** [comment]
@pmonks - any thoughts on the design approach?

**Comment by pmonks** [comment]
I'm very much in favour of a "map-based" representation of the license and exception lists held by the library and accessible (perhaps only as an unmodifiableMap, so callers can't modify that core data and mess things up?) via a public API; FWIW my code constructs exactly these maps itself so this would be a (welcome!) simplification of my code.

One thought: there may be runtime performance benefits for the library to make more use of such a map itself e.g. in various methods in the `org.spdx.library.model.license.ListedLicenses` class (note: I'm looking at the 1.1.12 version of the code right now - I believe that class has changed packages and/or names in v2.0). For example determining whether an id is valid, or retrieving an `org.spdx.library.model.license.SpdxListedLicense` instance for a given id.

**Comment by dwalluck** [comment]
> > I quickly tried to test 2.0.0-RC1 and I got a fatal error loading the cached SPDX licenses...
> 
> I wasn't able to duplicate the problem.
> 
> The warning is expected if you're not connected to the internet. The hard error, on the other hand, is completely unexpected.
> 
> I'll add some additional logging to see if we can find out what is wrong.
> 
> The code just reads the license information from resource files included in the Jar file.

I was definitely connected to the internet. Making the error message show the exception stack trace would be helpful.

**Comment by dwalluck** [comment]
```
ava.lang.RuntimeException: Unexpected error loading SPDX Listed Licenses
        at org.spdx.library.ListedLicenses.initializeLicenseModelStore(ListedLicenses.java:130)
        at org.spdx.library.ListedLicenses.<init>(ListedLicenses.java:77)
        at org.spdx.library.ListedLicenses.getListedLicenses(ListedLicenses.java:155)
Caused by: org.spdx.core.ModelRegistryException: No implementation found for SPDX spec version 3.0.1
        at org.spdx.core.ModelRegistry.typeToClass(ModelRegistry.java:194)
        at org.spdx.core.TypedValue.<init>(TypedValue.java:31)
        at org.spdx.storage.listedlicense.LicenseCreatorAgent.<init>(LicenseCreatorAgent.java:55)
        at org.spdx.storage.listedlicense.SpdxListedLicenseModelStore.<init>(SpdxListedLicenseModelStore.java:118)
        at org.spdx.storage.listedlicense.SpdxListedLicenseLocalStore.<init>(SpdxListedLicenseLocalStore.java:37)
        at org.spdx.library.ListedLicenses.initializeLicenseModelStore(ListedLicenses.java:127)
        ... 6 more
```

**Comment by dwalluck** [comment]
@goneall I tracked it down to missing calls to `SpdxModelFactory.init()` and `DefaultModelStore.initialize()` in my application (it apparently needs both). I am not sure about the proper arguments to `DefaultModelStore.initialize()` as neither of these methods used to be necessary. I believe that a call to `ListedLicenses.getListedLicenses()` took care of the initialization before so it looks like some sort of regression.

**Comment by goneall** [comment]
> [@goneall](https://github.com/goneall) I tracked it down to missing calls to `SpdxModelFactory.init()` and `DefaultModelStore.initialize()` in my application (it apparently needs both). I am not sure about the proper arguments to `DefaultModelStore.initialize()` as neither of these methods used to be necessary. I believe that a call to `ListedLicenses.getListedLicenses()` took care of the initialization before so it looks like some sort of regression.

Yes - these are now required with the redesign to support SPDX 3.0.

I don't know if there is a better way to initialize the model registry so we don't have to call `SpdxModelFactory.init()`.  It is a static method, so it only needs to be called once.  The new design has a registry of supported model implementations which are implemented in external Jar files.  We need to register those before any models are accessed.  Let me know if you have any ideas on a better approach rather than calling `SpdxModelFactory.init()`.

We probably could put back the default default model store initializations.  At one point, we restricted the model store to only store one major version - in other words, you had to choose whether the default would store SPDX spec version 2.X exclusive or SPDX spec version 3.X.  This is no longer true - you can now store both versions in the same model store - so the defaults can be added back.

**Comment by goneall** [comment]
I added #284 to track adding back a default store.

**Comment by goneall** [comment]
@dwalluck - We might need the `SpdxModelFactory.init()` to initialize the default model store.  See https://github.com/spdx/Spdx-Java-Library/issues/284#issuecomment-2613527442

**Comment by dwalluck** [comment]
> [@dwalluck](https://github.com/dwalluck) - We might need the `SpdxModelFactory.init()` to initialize the default model store. See [#284 (comment)](https://github.com/spdx/Spdx-Java-Library/issues/284#issuecomment-2613527442)

Actually, I thought it had something to do with the split between the core and the library, since it used to be set to `new InMemSpdxStore()` by default, which is now in the core. But, can't the library set this instead of the core now?

**Comment by goneall** [comment]
There are a few design choices to make in implementing the map.

Note that with the large number of licenses, there is a high performance penalty to constructing all of the licenses from the source JSON files.

- Do we create the map as a static block?  Personally, I think the performance penalty is too high, so it should be constructed only if the full map is retrieved.
- Do we need 4 maps (V2 licenses, V2 exceptions, V3 licenses, V3 exceptions)? - I'm thinking all 4 are useful.
- Should we store the maps in the `ListedLicenses` class or in the `SpdxVXListedLicenseModelStore`? - I'm thinking the latter provides better locality for the data.
- If we don't construct that maps as a static block, should we start filling the map on individual license requests - basically using it as a cache and only filling the entire map if the full map is fetched?  This would be more complex and require locking, but it would speed up the individual license and exception fetches and reduce the time for the full map fetch in certain scenarios.


@pmonks @dwalluck - let me know your thoughts on the above.

**Comment by dwalluck** [comment]
I hope I am envisioning this correctly.

I think that you already have the caches in `SpdxVXListedLicenseModelStore`, so on the first call to the `getXMap` API, i.e., when `map == null`, it could fill the cache, then copy that data into `map`. Otherwise, it would just return the existing `Collections.unModifiableMap(map)`.

My thinking is that the cache is filled on request, but the listed licenses are not. Doesn't everything require the full list? The methods I was thinking of are the ones off of `ListedLicenses.getListedLicenses().*` and not off of `ListedLicenses` itself, so maybe I am not following something when you say "start filling the map on individual license requests".

**Comment by pmonks** [comment]
Disclaimer: I haven't worked with SPDX models yet, so some of this may be hopelessly naive.

My first question would be whether the listed licenses and exceptions need to be shoehorned into the SPDX model at all - can they instead just be stored in their own separate structure(s) directly modeled on the license and exception list JSON (which, afaik, does not use the SPDX model and is therefore not sensitive to any SPDX model version)?

Obviously SBOMs that contain components that are licensed with listed licenses and exceptions need to be able to refer to those somehow, but I was under the (perhaps mistaken) impression that that is typically done via a simple scalar string SPDX License (or License Exception) Identifier; that the listed license (or exception) didn't have to be "fully hydrated" into the user's SBOM (though for convenience, perhaps such a mapping function could be provided by the library, independent of how those lists are natively stored, so users who do need to hydrate listed licenses/exceptions into their own SPDX model can do so easily?).

The reason I bring this up is that it addresses your second point about a combinatorial explosion in the number of lists that need to be cached by the library, by simply having one of each (licenses and exceptions), in their native formats (i.e. not in any particular version of the SPDX model).

As for initialisation (bullet points 1 & 4) - yes this is a substantial cost, especially as the file count is something like 4x the number of listed licenses and exceptions (text template, HTML template, matching XML template, header template, etc.).  In fact this is the reason I wrote that download cache a while back - my own tests found that downloading the license and exception lists, plus all the ancillary files per license/exception, was prohibitive. IOW I think initialising the lists in a static block would be a mistake, not least because throwing exceptions inside static blocks in Java is nasty (and downloading and parsing the lists can throw various I/O and JSON exceptions for reasons beyond the control of the library e.g. transient environmental issues such as spotty network connectivity, corrupted downloads, etc.).

What I've done in my own code is provide an (optional) explicit `init` function for both lists, while also performing lazy initialisation on first use if users elect not to call `init` explicitly. This gives users the option about when to incur the cost of initialisation (if they need that), while still ensuring that initialisation happens regardless. I should also mention that this is trivial to do in Clojure (via a thing called a "delay"), but I suspect may be harder to implement properly in Java (especially taking multithreading into account)...

Regarding bullet point 4 specifically, I'm a little nervous about concurrency bottlenecks with a lazy approach like that, especially as the download cache (in many cases) massively reduces the cost of reading those files and loading/parsing them into in-memory structures.  In the spirit of avoiding the sin of premature-optimisation I'd probably rather see a simple/obvious "load everything" implementation first, and only if/when it is proven to be too costly might we consider a lazier approach (especially as this will presumably need a custom `java.util.Map` implementation, and that's not a small undertaking).

**Comment by goneall** [comment]
Thanks @pmonks and @dwalluck for the comments.  I'll respond to some of the specifics in separate comments, but one common thread is the question of inflating the full model representation of the license.

The code currently fetches all the license and exception ID's along with some minimal information for all licenses and exceptions upfront - this is reasonably efficient since the information is stored in 2 JSON files and it is a simple deserialization with possibly 2 network IO's to fetch the latest.

So - when you call a function like `getSpdxListedLicenseIds()` or `isSpdxListedLicenseId(String licenseId)` there is almost no overhead.

It is only when you call a function like `getListedLicenseById(String licenseId)` that the full license is fetched.

**Comment by goneall** [comment]
I did a bit more looking at the code and the loading of the listed license properties is lazy, so there is almost no cost to create the above referenced maps.  It won't even hit the network cache unless there is a property inside a listed license or exception that is accessed.

I'm going to run an experiment just to confirm - but we should be able to create the maps as a field in the `ListedLicenses` singleton.

**Comment by goneall** [comment]
When I first ran the test, I found out it wasn't quite as lazy as I thought, but after a quick fix the time it took to create a map of all licenses was 300ms on my local development machine.  

So - no need for a complex caching approach.  I'll just fetch on first call to the method and keep it around for future calls.

I'll create a PR for review.

**Comment by goneall** [comment]
I created a PR to return maps for the licenses and exception - please see PR #290 

I ran into another performance issue - just with the SPDX spec version 2 model - https://github.com/spdx/spdx-java-model-2_X/issues/13

It takes about 15 seconds to execute on my computer.  If you think a fix is needed, please leave a comment in https://github.com/spdx/spdx-java-model-2_X/issues/13

**Comment by dwalluck** [comment]
> It is only when you call a function like `getListedLicenseById(String licenseId)` that the full license is fetched.

Thanks for reminding me. This is essentially what I do in my code:

```java
private static Map<String, ListedLicense> LICENSE_IDS_MAP;
for (String id : LicenseInfoFactory.getSpdxListedLicenseIds()) {
    ListedLicense listedLicense = LicenseInfoFactory.getListedLicenseById(id);
    // XXX: Can id != listedLicense.toString()?
    LICENSE_IDS_MAP.put(listedLicense.toString(), listedLicense);
}
```

I should note that these two calls can both hit the network and I seem to get intermittent network failures, so I actually retry them.

Also, I am using a `LinkedHashMap` with the ids sorted by length and then name. This way, if there's more than one match, like a license with a built-in exception, it will chose the first (shortest) one. I am not sure if that's the best algorithm. but, in any case, I am going to have to rebuild the map from whatever the API will provide.

**Comment by goneall** [comment]
@dwalluck - since you're going to rebuild the map, I think I'll keep the hashmap for the slight performance gain on fetching the exact ID's.

Now that the initial loading of the hash maps are reasonably fast, I think I'll change the getters in the `ListedLicenses` class to use the hashmaps.
