### ISSUE TITLE
License parsing fails for expressions containing a plus sign

### ISSUE THREAD

**Issue by javierfreire** [spdx/Spdx-Java-Library#256]
When parsing license expressions that include a + symbol, such as GPL-3.0-only WITH autoconf-exception+, the library throws an exception:

```java
LicenseInfoFactory.parseSPDXLicenseString("GPL-3.0-only WITH autoconf-exception+");
```

```
Exception in thread "main" org.spdx.library.model.license.InvalidLicenseStringException: Missing license for the '+' or later operator License expression: 'GPL-3.0-only WITH autoconf-exception+'
	at org.spdx.library.model.license.LicenseInfoFactory.parseSPDXLicenseString(LicenseInfoFactory.java:88)
	at org.spdx.library.model.license.LicenseInfoFactory.parseSPDXLicenseString(LicenseInfoFactory.java:111)
	at com.vmware.mapbu.cp.verification.puzzle.action.spdx.cli.TrivyTest.main(TrivyTest.java:181)
Caused by: org.spdx.library.model.license.LicenseParserException: Missing license for the '+' or later operator License expression: 'GPL-3.0-only WITH autoconf-exception+'
	at org.spdx.library.model.license.LicenseExpressionParser.parseLicenseExpression(LicenseExpressionParser.java:94)
	at org.spdx.library.model.license.LicenseInfoFactory.parseSPDXLicenseString(LicenseInfoFactory.java:86)
	... 2 more
Caused by: org.spdx.library.model.license.LicenseParserException: Missing license for the '+' or later operator
	at org.spdx.library.model.license.LicenseExpressionParser.evaluateExpression(LicenseExpressionParser.java:317)
	at org.spdx.library.model.license.LicenseExpressionParser.parseLicenseExpression(LicenseExpressionParser.java:218)
	at org.spdx.library.model.license.LicenseExpressionParser.parseLicenseExpression(LicenseExpressionParser.java:91)
	... 3 more
```

**Comment by pmonks** [comment]
That's correct behaviour. [The ABNF for license expressions](https://spdx.github.io/spdx-spec/v3.0.1/annexes/spdx-license-expressions/) only allows `+` to be used with a license identifier, not an exception identifier. They also can't be used with LicenseRefs or AdditionRefs.

**Comment by javierfreire** [comment]
You're right, thank you for your attention and sorry for the inconvenience.

**Comment by pmonks** [comment]
No worries! I can see why it _might_ make sense to allow `+` for exception ids, though that would need further discussion with the spec folx (there may be very good reasons this isn't allowed that I'm unfamiliar with).
